### ISSUE TITLE
placeholder to yaml map

### ISSUE THREAD

**Issue by microconfig** [microconfig/microconfig#17]
Placeholders should allow to reference not only to a single value, but to multiple values as well.

Example:
```
key1:
  key2: 2
  key3: 3

link:
  \${this@key1.*}
```
result:
```
link:
 key1:
  key2: 2
  key3: 3
