### ISSUE TITLE
Property sorting in yaml

### ISSUE THREAD

**Issue by kapodes** [microconfig/microconfig#3]
Currently properties are sorted in alphabetic order like

```
cloud:
  kubernetes:
    discovery:
      catalog-services-watch:
        catalogServicesWatchDelay: 10000
          enabled: true
      enabled: true
```

Better to first sort properties on number of sub-properties and then alphabetically.
Should improve readability.

```
cloud:
  kubernetes:
    discovery:
      enabled: true
      catalog-services-watch:
        catalogServicesWatchDelay: 10000
          enabled: true
```
